### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by fabston** [SwissCorePy/pyTelegramBotCAPTCHA#11]
Hi there,

Great work - loving your captcha bot! I had one idea that would be great to implement. A `Refresh` button in case the captcha is really hard / barley readable.

Keep it up!

**Comment by coder2020official** [comment]
Hi!
I liked your idea.  I will work on it :)
Thank you for idea

**Comment by coder2020official** [comment]
I am not sure of this PR, it would be good if you help in testing :)
