### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by TheAwiteb** [SwissCorePy/pyTelegramBotCAPTCHA#13]
Hello, I think you forgot to update the (Arabic language) added in pypi

**Comment by coder2020official** [comment]
Hi, i am not maintainer on pypi :/
However, @SwissCorePy should review my pull request also :)

**Comment by SwissCorePy** [comment]
> Hello, I think you forgot to update the (Arabic language) added in pypi

new version 1.1.0 is out now. including arabic language. Thank you :)
