### ISSUE TITLE
No timeout anymore when user has made a wrong attempt

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#16]
There seems to be an error where there is no timeout event anymore when a user made a wrong attempt, it also seems to not work anymore when a user manually refreshed the CAPTCHA. It still happens though when a user is still on the initial CAPTCHA. I tried this with the default timeout of 90, and a custom timeout. Note that `max_incorrect_to_auto_reload` has been set to 1, so a timeout should still happen.

**Comment by coder2020official** [comment]
Oh, looks like a bug

**Comment by SwissCorePy** [comment]
Yes looks like a bug. We will try to fix it ASAP. Thanks for report

**Comment by tinderboxmedia** [comment]
> Yes looks like a bug. We will try to fix it ASAP. Thanks for report

Thanks! Like I mentioned before, if I had the skills I would fix it myself so I can actually contribute to this repo.

**Comment by SwissCorePy** [comment]
> > Yes looks like a bug. We will try to fix it ASAP. Thanks for report
> 
> Thanks! Like I mentioned before, if I had the skills I would fix it myself so I can actually contribute to this repo.

No problem ^^
Its fixed now in new version 1.1.1
