### ISSUE TITLE
KeyZenD returns a 404. Fallback to 'Default' might be needed.

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#18]
Seems like the KeyZenD CAPTCHA can't be found anymore: https://tyt.xyeta.ml/captcha.png

This page returns an 404, and the CAPTCHA can't be found. Maybe it would be smart to add some sort of fallback that turns the option back to 'default' as currently this would break the entire thing?

**Comment by coder2020official** [comment]
Hello!
I will contact him, thank you for report.

**Comment by coder2020official** [comment]
Website is already working, you can continue

**Comment by tinderboxmedia** [comment]
Thanks! Some sort of fallback mechanism to 'default' in case of a KeyZenD 404 would be appreciated though.
