### ISSUE TITLE
Suggestion: Be able to declare the length of the captcha

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#4]
Currently the length of the captcha showed is defaulted and hardcoded to be 8 characters long. The suggestion would be to be able to declare the length of the captcha, so that it can display less or even more characters that need to be solved.

**Comment by SwissCorePy** [comment]
Thanks for your suggestion. we will intergrate that but may with a limit form 4-12 characters. What do you think?

**Comment by tinderboxmedia** [comment]
That range seems perfect as a captcha with less than 4 wouldn't really be a captcha and more than 12 would be way to difficult. Much appreciated! I would fork the project myself, but I'm not skilled enough yet in order to really contribute.

**Comment by SwissCorePy** [comment]
no problem. we will do this in a near future release.

**Comment by SwissCorePy** [comment]
I updated the package. in version 1.03 you are able to set the parameter `code_length` in captcha_manager. It must be at least 4 and maximum 12.
