### ISSUE TITLE
Inconsistency: A captcha reload on an incorrect submit has default values

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#5]
If an individual fails to solve the captcha and if another attempt is allowed, the captcha will refresh but it will override variables such as timeout, digits_only and add_noice. This feels like an inconsistency in the logic as a refresh should give a new captcha but with all the user declared variables and values. If the function is declared to not add_noice or to be digits_only, a refresh should not change this behaviour, unless declared otherwise.

To fix this inconsistency the captcha refresh should either follow the user declared variables and values, or one should be able to allow this override to happen or not.

**Comment by SwissCorePy** [comment]
the idea behind this is the possibility to give the user a harder or easier captcha to solve after x tries. so this is behaviour is intentional

**Comment by tinderboxmedia** [comment]
That does make sense actually. Would it be possible though to add an option to override this intentional behaviour?

**Comment by SwissCorePy** [comment]
i could implement a second refresh function that uses the same settings like the previous one. what do you think?

**Comment by tinderboxmedia** [comment]
That would be perfect! Thanks.

**Comment by SwissCorePy** [comment]
I updated the package. in version 1.03 `refresh_captcha` uses the previous captcha settings if not set again.
