### ISSUE TITLE
Suggestion: Be able to declare the digits and hex-digits used in the captcha outside of the module

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#6]
Currently the only way to change the digits and hex-digits used in the captcha is to change variables inside of the module. The suggestion would be to be able to declare which digits or letters can be used, but still in a set of 10 (the 2 by 5 input markup grid), or a set of 16 (the 4x4 input markup grid).

The main reason for this suggestion is that some fonts do have characters that could potentially look to similar. For example: 8 and B, or 1 and 7. Be able to declare a custom set of 10 or 16 characters, the captchas could become more user friendly but still bot proof.

**Comment by SwissCorePy** [comment]
if you import `telebot_captcha` you are able to set `telebot_captcha.digits = "xxxxxxxxxx"` or `telebot_captcha.hexdigits = "xxxxxxxxxxxxxxxx"` the markup and the code generator will use the declared chars.

**Comment by SwissCorePy** [comment]
i did not try this but it should work

**Comment by tinderboxmedia** [comment]
You're right! That did actually work. I tried to do that before, but I wasn't smart enough to actually import `telebot_captcha`. Closing this as there is no need for extra functionality. Thanks again.

**Comment by SwissCorePy** [comment]
I just remembered, the built in fonts currently onla contain hexdigits (in order to use less memory). so I will replace them to support all alphanumeric characters.
