### ISSUE TITLE
Issue: Adding 1+ users to the channel will only trigger 1 captcha

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#7]
After some more stress testing it seems to be the case that if someone invites or adds more than 1 user (the option to mass invite your contacts to a channel for example) to the channel where the bot is active, it will only create 1 captcha. Only one user has to complete the captcha, the other users are already 'in' (so to speak).

**Comment by SwissCorePy** [comment]
yes you have to loop through the new users. 
![Bildschirmfoto 2021-07-05 um 15 01 32](https://user-images.githubusercontent.com/51398037/124475356-ea946900-dda1-11eb-9e0f-4d6dc09db11f.png)

**Comment by tinderboxmedia** [comment]
I see, I used one of the example  scripts, the windows one did not have the loop. Thank you!

**Comment by SwissCorePy** [comment]
oh i have to update the example script. thank you
