### ISSUE TITLE
Issue: If a captcha is not properly removed after kicking a user, it will throw a KeyError when trying to interact with it again

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#8]
While interacting with a captcha button (update_captcha), it should first be checked if that captcha session is still 'available' or not. It not being 'available' can be due to that the captcha message was not deleted properly after kicking a user and that user did not solve it, or that the file that holds that captcha session is somehow removed.

Right now it will throw a KeyError if the session can't be found, but if we can check if that captcha session is not available anymore,  we could just remove the captcha instead (whoever presses it) and clean up.

**Comment by SwissCorePy** [comment]
The captcha should always be deleted properly using captcha_manager.delete_captcha(...) to avoid this error.
But you can check manually if f"{bot_id}={callback.message.chat.id}={user_id}" in captcha_manager.captchas

**Comment by tinderboxmedia** [comment]
With some minor changes this indeed worked. Thanks!
