### ISSUE TITLE
Issue: Adding the code_length argument to send_random_captcha will throw a TypeError.

### ISSUE THREAD

**Issue by tinderboxmedia** [SwissCorePy/pyTelegramBotCAPTCHA#9]
For example, trying initialize the captcha using `captcha_manager.send_random_captcha(bot, message.chat, new_user, timeout=60, code_length=4, language="en")` will result in `TypeError: send_random_captcha() got an unexpected keyword argument 'code_length'`

However, following the documentation this should be possible.

**Comment by SwissCorePy** [comment]
you have to set code length in captcha_manager = CaptchaManager() not in send_random_captcha

**Comment by tinderboxmedia** [comment]
Seems like I need to read better. You're right. My apologies!
